addons:
  code_climate:
    repo_token: fd4f98a0b879612c6384c111a73a31b5be9c63df23fc0a1ffd02f9fadc8c7f24
after_success:
  - bundle exec codeclimate-test-reporter
sudo: false
language: ruby
rvm:
  - 2.4.0
  - 2.3.0
  - 2.2.0
  - 2.1
before_install: gem install bundler --pre
